#########################
# Spring Boot
#########################
server:
    port: 6969 #应用启动端口

spring:
    application:
        name: gen-demo  #应用名称

    #jackson配置
    jackson:
        serialization:
            INDENT_OUTPUT: true # jackson格式化输出
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # 数据库配置，不使用数据库时请删除以下配置
    datasource:
        # 使用MySQL数据库
        driver-class-name: com.mysql.cj.jdbc.Driver
        # MySQL数据库连接URL
        url: jdbc:mysql://200.3.205.39:3306/code_gen?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        type: com.zaxxer.hikari.HikariDataSource #datasource使用的连接池类型
        validation-query: SELECT 1 FROM DUAL #datasource连接验证的查询语句
        username: root #数据库连接的用户名
        password: root #数据库连接的密码
        hikari:
            minimum-idle: 2                 # 空闲时最小连接数
            maximum-pool-size: 2            # 连接池大小
            data-source-properties:
                cachePrepStmts: true        # 是否启用Prep缓存
                prepStmtCacheSize: 250      # Prep缓存大小
                prepStmtCacheSqlLimit: 2048 # Prep缓存sql限制大小
                useServerPrepStmts: true    # 是否用服务缓存Prep
    # 数据库配置，不使用数据库时请删除以上配置

# mybatis  配置
#########################
mybatis:
    mapperLocations: classpath*:mapper/**/*.xml # mybatis对应的xml文件路径
    configuration:
        map-underscore-to-camel-case: true      # 是否开启驼峰命名